sudo: required
language: go

go:
  - "1.12"

install:
  - go get -d github.com/antonkrug/ead

env:
  global:
    # Setting timestamp
    - TS=$(date +"%Y%m%d-%H%M%S")
  
script:
  - bash ./build_all_platforms.sh

deploy:
  provider: releases
  api_key:
    secure: n5Ob15v9c1NZJ5OEBNw5gqYvvpLq8FIfHehKRIirznLi2+SKBmI2GTePz66euY8+7s2x+IdyekaJbkd2Mnf79dy92XB52tkJKLdceOj2b+19nMzbjYGZdNzXjF/wv75LE7VIaBKfNUArNcO0TIQc67mhpBVNyxn37SuC8PK8ImI7Vkje6B04IpNrwyGIxrQ2uQPP8VcI2Y+ZmIAU24ESsrWdJrAvO27oahqgdcckd0jy/xt8uhGX3W5v5Y2MO5hVr/I4bTjpaEFOJpveGBBZtgKKivdP9nU3MXbnEmkCS+VQlXLAJSOCAT4ZFRgBw8C/VWmLjej2XAa2rCPy2LubYwi4O2SaFCh/8YYd1RLbFj5QFQ1xtvqIxWi+ZcJAOaz+/IuMtGNIh5GPX89aTpq2OOsOGnQb1nV5aAAimbpvxj2xLp4ULxsisw5okeLdcPUYeahG3knw69g5pn9CIfOPvxnI3Up0/d697FjsqJT+XDopkFoUUHHyO47V2tpFUkhzHJYqJtRAJxkyMQH0UgdPA0rbNcV2j9tmju9GjcA+jWgyTJzydAn7Ajjxai+c/dZ2wbcBTlwBY0cwWRZDwEPJTDkOydncKrUJo94YBuVSVCVUY6sAFb/RVxJM0oBuPJTXw84T6RI45ceHTBTft3mvNhErUMGwxs6vfkuQx+AuFM0=
  file:
    - "release/ead-windows-x86-64-$TS.exe"
    - "release/ead-windows-x86-32-$TS.exe"
    - "release/ead-windows-arm-$TS.exe"
    - "release/ead-linux-x86-64-$TS"
    - "release/ead-linux-x86-32-$TS"
    - "release/ead-linux-arm-64-$TS"
    - "release/ead-linux-arm-32-$TS"
    - "release/ead-freebsd-x86-64-$TS"
    - "release/ead-freebsd-x86-32-$TS"
    - "release/ead-macos-x86-64-$TS"
    - "release/ead-macos-x86-32-$TS"
  skip_cleanup: true
  on:
    tags: true