/*
 * {{COPYRIGHT}}
 *
 * Generated on: {{GENERATED_DATE}}
 * {{EAD_COMMENT_NOTICE}}
 */

#ifndef EMBEDDED_AUTOGENERATED_DATA_{{FILENAME_H}}_H_
#define EMBEDDED_AUTOGENERATED_DATA_{{FILENAME_H}}_H_

#include "{{INCLUDE_PREFIX}}/ead_structures.h"

static const unsigned char {{EAD_FILENAME_VARIABLE}}[{{DATA_SIZE}}] =
{
    {{DATA_CONTENT_HEX_DUMP}}
};


static const ead_item_t {{EAD_FILENAME_VARIABLE_METADATA}} = 
{
    .location             = "{{ORIGINAL_PATH}}",
    .content_type         = "{{CONTENT-TYPE}}",
    .web_content_encoding = {{WEB_CONTENT_ENCODING}},
    .data                 = {{EAD_FILENAME_VARIABLE}},
    .size                 = {{DATA_SIZE}}
};

#endif /* EMBEDDED_AUTOGENERATED_DATA_{{FILENAME_H}}_H_ */
