/*
 * {{COPYRIGHT}}
 *
 * Generated on: {{GENERATED_DATE}}
 * {{EAD_COMMENT_NOTICE}}
 */

#ifndef EMBEDDED_AUTOGENERATED_DATA_EAD_COLLECTION_H_
#define EMBEDDED_AUTOGENERATED_DATA_EAD_COLLECTION_H_

#include "ead_structures.h"


{{{INCLUDE_FILES}}}

static const ead_item_t static_data_index[] = 
{
{{METADATA_ENTRIES}} 
};

#define STATIC_DATA_INDEX_SIZE (sizeof(static_data_index) / sizeof(static_data_index[0]))

#endif /* EMBEDDED_AUTOGENERATED_DATA_EAD_COLLECTION_H_ */
